micronaut:
  application:
    name: micronaut_jwt_rest_api_project
  server:
    port: 9999

---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 0003pray
    initial-pool-size: 5
    maximum-pool-size: 100
    minimum-idle: 5

---
micronaut:
  inject:
    post-construct: true

---
flyway:
  baselineOnMigrate: true
  datasources:
    default:
      enabled: true

---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger/swagger-ui-4.18.1
        mapping: /swagger/**
swagger:
  endpoints:
    swagger-ui:
      enabled: true
      base-path: /swagger
    api:
      enabled: true
      base-path: /api



