micronaut:
  server:
    port: 9998
  application:
    name: micronaut_jwt_rest_api_demo
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}

datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 0003pray
    db-type: mysql
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    packages-to-scan:
      - 'com.jwt.rest.api.entities'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
