micronaut:
  server:
    port: 9999
  application:
    name: micronautProject

datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 0003pray


netty:
  default:
    allocator:
      max-order: 3
